rv64: Add support for Zba, Zbb, Zbc, Zbs
aengelke/rellume pull request #14
Opened 2024-05-11 10:21 UTC by TimaFrolov

This PR adds support for [bitmanip](https://github.com/riscv/riscv-bitmanip) extensions of RISC-V architecture.
I've sent you patchset for frvdec with necessary updates for this PR to work. You can also see changes in [my fork of your repo](https://git.sr.ht/~timafrolov/frvdec)

2024-06-07 15:31 UTC, aengelke requested changes
Looks good, thanks! A few nits, then this should be good to merge. Sorry for the delay.

2024-06-16 18:46 UTC, TimaFrolov commented on src/rv64/lifter.cc
> +        auto rhs = irb.CreateShl(irb.getInt64(1), index);
Yea, assuming width == 64 is fine. Fixed

2024-06-16 18:46 UTC, TimaFrolov commented on src/rv64/lifter.cc
> +        auto res = irb.CreateAnd(irb.CreateLShr(LoadGp(rvi->rs1), index), irb.getInt64(1));
Done

2024-06-16 18:47 UTC, TimaFrolov commented on src/rv64/lifter.cc
> +        enter_block->BranchTo(*loop_block);
Done

2024-06-16 18:51 UTC, TimaFrolov commented on src/rv64/lifter.cc
> +        enter_block->BranchTo(*loop_block);
Done
I just thought that producing that much code for a single instruction could result in code bloat. Clang doesn't unroll this all the way even with -O3 option
Not sure if there could me that many of these instructions in real-world code to think about it though

2024-06-17 08:46 UTC, aengelke approved these changes

2024-06-17 08:47 UTC, merged

2024-06-17 15:34 UTC, aengelke commented on src/rv64/lifter.cc
> +        enter_block->BranchTo(*loop_block);
The point is that the back-end might be able to fold it back into the original instruction if everything is in a single basic block. There's no pattern matching across basic blocks.